### ISSUE TITLE
Samples missing important classes

### ISSUE THREAD

**Issue by Imar** [dojo-engineering/dojo-samples#18]
Hi there,

These samples reference all kinds of classes like WebhookPayloadUtils and specific clients. However that code doesn't seem to be in this repo making it useless as a sample, and hard to figure out how to do something like signature verification. Also, on the official Github docs page for Dojo.Net it mentions classes like PaymentIntentsClient. However, I can't find source code for that either. Am I missing something or has this never been published?

I found another issue reported here: https://github.com/dojo-engineering/Dojo.Net/issues/1 that says that the SDK isn't what it claims to be. Is it worth pursuing this or should I give up and write my own library code? It would be nice if there was a stable and officially supported SDK as it would make it simple, safe and fun to implement Dojo.

Thanks,

Imar

**Comment by RomanKondratyev** [comment]
Hi @Imar,

I will add support for .net standard 2.0 - it should be easy.

Thanks,
Roman
