### ISSUE TITLE
Flow for epos and terminal

### ISSUE THREAD

**Issue by tmblog** [dojo-engineering/dojo-samples#54]
Hi what's the basic flow for creating a transaction from an epos to a dojo terminal? I'm using python.

**Comment by martinhay1** [comment]
Hi @tmblog 
Please find the basic flow and general information [here](https://docs.dojo.tech/payments/accept-payments/in-person-payments/pay-at-counter/introduction).
Unfortunately we don't currently have any python examples.
Thanks!

**Comment by monica-m-ps** [comment]
Closing issue as currently we don't have Python code samples
